### ISSUE TITLE
install_script issues

### ISSUE THREAD

**Issue by larsbo** [shopwareLabs/shopware-vagrant#9] opened 2016-09-08 10:56 UTC
First the install_script path inside the vagrant box is `bin/install_script` while the readme says just `install_script`. But running ./bin/install_script just outputs the error `not found`.

Running the tasks from the script manually works but the ant task misses jdk so i installed `openjdk-7-jdk` first.

OS: Windows 10
Virtual Box: 5.1.4
Vagrant: 1.8.5

**Comment by Gugiman** [comment] 2016-09-08 12:11
same here for changephp_*:

> vagrant@shopware:~$
vagrant@shopware:~$
vagrant@shopware:~$ changephp_5.6
: No such file or directory
vagrant@shopware:~$
vagrant@shopware:~$

**Comment by bcremer** [comment] 2016-09-08 12:23
@larsbo what is the output of `echo $PATH`?
Please also try `vagrant provision`.

**Comment by Gugiman** [comment] 2016-09-08 13:36
/home/vagrant/bin:/home/vagrant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

I can call changephp_5.6 from anywhere but then nothing happens.

**Comment by bcremer** [comment] 2016-09-08 13:42
Ok got it.
It seems like the newlines got screwed up during checkout. I suppose you checked the repo out on a windows machine?

Can you please run the following command and test the scripts again:

``` 
sed -i 's/\r//' /home/vagrant/bin/*
```

**Comment by Gugiman** [comment] 2016-09-08 13:47
Good Catch.
Yes that's right.
Just installed dos2unix to test but I think your snippets does the same.

Now everything runs fine.

**Comment by bcremer** [comment] 2016-09-08 13:50
This commit should fix the issue: https://github.com/shopwareLabs/shopware-vagrant/commit/ee33bbed6abb2d8631166e1c835d8b6f1f8a86e4

You might have to do a fresh checkout.

**Comment by larsbo** [comment] 2016-09-08 18:20
I did a fresh shopware-vagrant installation but I still got the error:
```
vagrant@shopware:~$ install_shopware
: No such file or directory
```

I used the git console from the official package available at http://git-scm.com:
```
$ git --version
git version 2.10.0.windows.1
```

**Comment by Gugiman** [comment] 2016-09-09 11:18
Same here after complete fresh clone.

git version 2.7.2.windows.1

> vagrant@shopware:~$
vagrant@shopware:~$ changephp_5.6
: No such file or directory
vagrant@shopware:~$

**Comment by bcremer** [comment] 2016-09-13 11:40
@larsbo @Gugiman my latest commit (https://github.com/shopwareLabs/shopware-vagrant/commit/0608537665e7bc9ab592759b6acd045ae30ebf3e) should fix this issue. 
Can you please test this with a fresh checkout.

Thanks in advance.

**Comment by Gugiman** [comment] 2016-09-14 07:24
Can confirm.
In my case the issue is solved.

Thanks for your effort!

**Comment by bcremer** [comment] 2016-09-14 07:35
Thanks for reporting back. I'll close this issue as resolved.

**Closed by bcremer** 2016-09-14 07:35 UTC
